### PR TITLE
added method lookup_statuses

### PR DESCRIPTION
**Pull request by jasonshaev**

### CODE REVIEW

**Comment by semifor** [comment]
Thanks for the pull-request!

**Comment by jasonshaev** [comment]
Thanks for the quick response! Cheers.

**Comment by semifor** [comment]
FYI, I added a1d13e8, so you can call `$nt->lookup_statuses({ id => \@ids })`. Net::Twitter will build the comma delimited `id` list from an ARRAY ref of ids, for you.

**Comment by semifor** [comment]
And...it's live: https://metacpan.org/release/MMIMS/Net-Twitter-4.01007

**Comment by jasonshaev** [comment]
Great, thanks. Sorry for the inconsistency with existing functions.

**Pull request merged**
